package services

import (
	"fmt"
	"strings"
	"time"
)

// GenerateDockerComposeYAML converts a list of services to docker-compose.yml
func GenerateDockerComposeYAML(services []DockerService) string {
	if len(services) == 0 {
		return "services: {}\n"
	}

	var sb strings.Builder
	sb.WriteString("# ==============================================================================\n")
	sb.WriteString("# Generated by DockCraft Studio (Go Backend Engine)\n")
	sb.WriteString(fmt.Sprintf("# Generated at: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("# ==============================================================================\n\n")
	sb.WriteString("services:\n")

	volumesSet := make(map[string]bool)
	networksSet := make(map[string]bool)
	networksSet["app-network"] = true

	for _, s := range services {
		sb.WriteString(fmt.Sprintf("  %s:\n", s.Name))
		sb.WriteString(fmt.Sprintf("    container_name: %s\n", s.Name))

		if s.IsCustomBuild {
			sb.WriteString("    build:\n")
			ctx := s.BuildContext
			if ctx == "" {
				ctx = "."
			}
			sb.WriteString(fmt.Sprintf("      context: %s\n", ctx))
			if s.DockerfilePath != "" {
				relPath := strings.TrimPrefix(s.DockerfilePath, ctx+"/")
				sb.WriteString(fmt.Sprintf("      dockerfile: %s\n", relPath))
			}
		} else {
			tag := s.Tag
			if tag == "" {
				tag = "latest"
			}
			sb.WriteString(fmt.Sprintf("    image: %s:%s\n", s.Image, tag))
		}

		if s.Restart != "" {
			sb.WriteString(fmt.Sprintf("    restart: %s\n", s.Restart))
		} else {
			sb.WriteString("    restart: unless-stopped\n")
		}

		if s.Command != "" {
			sb.WriteString(fmt.Sprintf("    command: %s\n", s.Command))
		}

		if s.User != "" {
			sb.WriteString(fmt.Sprintf("    user: \"%s\"\n", s.User))
		}

		// Ports
		if len(s.Ports) > 0 {
			sb.WriteString("    ports:\n")
			for _, p := range s.Ports {
				proto := ""
				if p.Protocol != "" && p.Protocol != "tcp" {
					proto = "/" + p.Protocol
				}
				sb.WriteString(fmt.Sprintf("      - \"%v:%v%s\"\n", p.HostPort, p.ContainerPort, proto))
			}
		}

		// Env
		if len(s.Env) > 0 {
			sb.WriteString("    environment:\n")
			for _, e := range s.Env {
				if e.IsSecret {
					sb.WriteString(fmt.Sprintf("      - %s=${%s:-%s}\n", e.Key, e.Key, e.Value))
				} else {
					sb.WriteString(fmt.Sprintf("      - %s=%s\n", e.Key, e.Value))
				}
			}
		}

		// Volumes
		if len(s.Volumes) > 0 {
			sb.WriteString("    volumes:\n")
			for _, v := range s.Volumes {
				ro := ""
				if v.ReadOnly {
					ro = ":ro"
				}
				sb.WriteString(fmt.Sprintf("      - %s:%s%s\n", v.HostPath, v.ContainerPath, ro))
				if v.Type == "volume" && !strings.HasPrefix(v.HostPath, ".") && !strings.HasPrefix(v.HostPath, "/") {
					volumesSet[v.HostPath] = true
				}
			}
		}

		// Depends On
		if len(s.DependsOn) > 0 {
			sb.WriteString("    depends_on:\n")
			for _, dep := range s.DependsOn {
				targetName := dep.ServiceID
				for _, target := range services {
					if target.ID == dep.ServiceID {
						targetName = target.Name
						break
					}
				}
				cond := dep.Condition
				if cond == "" {
					cond = "service_started"
				}
				sb.WriteString(fmt.Sprintf("      %s:\n", targetName))
				sb.WriteString(fmt.Sprintf("        condition: %s\n", cond))
			}
		}

		// HealthCheck
		if s.HealthCheck != nil && s.HealthCheck.Enabled && s.HealthCheck.Test != "" {
			sb.WriteString("    healthcheck:\n")
			sb.WriteString(fmt.Sprintf("      test: [\"CMD-SHELL\", \"%s\"]\n", s.HealthCheck.Test))
			interval := s.HealthCheck.Interval
			if interval == "" {
				interval = "10s"
			}
			timeout := s.HealthCheck.Timeout
			if timeout == "" {
				timeout = "5s"
			}
			retries := s.HealthCheck.Retries
			if retries == 0 {
				retries = 3
			}
			sb.WriteString(fmt.Sprintf("      interval: %s\n", interval))
			sb.WriteString(fmt.Sprintf("      timeout: %s\n", timeout))
			sb.WriteString(fmt.Sprintf("      retries: %d\n", retries))
		}

		// Networks
		sb.WriteString("    networks:\n")
		sb.WriteString("      - app-network\n\n")
	}

	// Networks block
	sb.WriteString("networks:\n")
	for net := range networksSet {
		sb.WriteString(fmt.Sprintf("  %s:\n    driver: bridge\n", net))
	}
	sb.WriteString("\n")

	// Volumes block
	if len(volumesSet) > 0 {
		sb.WriteString("volumes:\n")
		for vol := range volumesSet {
			sb.WriteString(fmt.Sprintf("  %s:\n    driver: local\n", vol))
		}
	}

	return sb.String()
}

// GenerateEnvFiles creates .env and .env.example contents
func GenerateEnvFiles(services []DockerService) (string, string) {
	var env strings.Builder
	var example strings.Builder

	env.WriteString("# ==========================================\n# DockCraft Environment Variables\n# ==========================================\n\n")
	example.WriteString("# ==========================================\n# DockCraft Environment Template (.env.example)\n# ==========================================\n\n")

	for _, s := range services {
		if len(s.Env) > 0 {
			header := fmt.Sprintf("\n# [%s]\n", strings.ToUpper(s.DisplayName))
			env.WriteString(header)
			example.WriteString(header)

			for _, e := range s.Env {
				desc := ""
				if e.Description != "" {
					desc = " # " + e.Description
				}
				env.WriteString(fmt.Sprintf("%s=%s%s\n", e.Key, e.Value, desc))
				if e.IsSecret {
					example.WriteString(fmt.Sprintf("%s=your_%s_here%s\n", e.Key, strings.ToLower(e.Key), desc))
				} else {
					example.WriteString(fmt.Sprintf("%s=%s%s\n", e.Key, e.Value, desc))
				}
			}
		}
	}

	return env.String(), example.String()
}
