package services

import "time"

// ServiceCategory defines the type of service
type ServiceCategory string

const (
	CategoryDatabase ServiceCategory = "database"
	CategoryBackend  ServiceCategory = "backend"
	CategoryFrontend ServiceCategory = "frontend"
	CategoryGateway  ServiceCategory = "gateway"
	CategoryQueue    ServiceCategory = "queue"
	CategoryTool     ServiceCategory = "tool"
	CategoryAI       ServiceCategory = "ai"
	CategoryCustom   ServiceCategory = "custom"
)

// PortMapping represents a port mapping
type PortMapping struct {
	ID            string      `json:"id"`
	HostPort      interface{} `json:"hostPort"`
	ContainerPort interface{} `json:"containerPort"`
	Protocol      string      `json:"protocol,omitempty"`
	Description   string      `json:"description,omitempty"`
}

// VolumeMapping represents a storage volume mount
type VolumeMapping struct {
	ID            string `json:"id"`
	HostPath      string `json:"hostPath"`
	ContainerPath string `json:"containerPath"`
	Type          string `json:"type"` // "volume" or "bind"
	ReadOnly      bool   `json:"readOnly,omitempty"`
	Description   string `json:"description,omitempty"`
}

// EnvVariable represents an environment variable
type EnvVariable struct {
	ID             string `json:"id"`
	Key            string `json:"key"`
	Value          string `json:"value"`
	IsSecret       bool   `json:"isSecret,omitempty"`
	Description    string `json:"description,omitempty"`
	AutoGenerated  bool   `json:"autoGenerated,omitempty"`
}

// HealthCheck represents container healthcheck configuration
type HealthCheck struct {
	Enabled     bool   `json:"enabled"`
	Test        string `json:"test"`
	Interval    string `json:"interval,omitempty"`
	Timeout     string `json:"timeout,omitempty"`
	Retries     int    `json:"retries,omitempty"`
	StartPeriod string `json:"startPeriod,omitempty"`
}

// ResourceLimits represents CPU and memory limits
type ResourceLimits struct {
	CPUs   string `json:"cpus,omitempty"`
	Memory string `json:"memory,omitempty"`
}

// Dependency represents a depends_on link
type Dependency struct {
	ServiceID string `json:"serviceId"`
	Condition string `json:"condition"` // "service_started", "service_healthy"
}

// DockerService is the complete configuration of a container
type DockerService struct {
	ID                      string          `json:"id"`
	Name                    string          `json:"name"`
	DisplayName             string          `json:"displayName"`
	Category                ServiceCategory `json:"category"`
	Image                   string          `json:"image,omitempty"`
	Tag                     string          `json:"tag,omitempty"`
	Icon                    string          `json:"icon"`
	Color                   string          `json:"color"`
	Description             string          `json:"description"`
	IsCustomBuild           bool            `json:"isCustomBuild"`
	BuildContext            string          `json:"buildContext,omitempty"`
	DockerfilePath          string          `json:"dockerfilePath,omitempty"`
	DockerfileType          string          `json:"dockerfileType,omitempty"`
	CustomDockerfileContent string          `json:"customDockerfileContent,omitempty"`
	Ports                   []PortMapping   `json:"ports"`
	Expose                  []int           `json:"expose,omitempty"`
	Networks                []string        `json:"networks"`
	Env                     []EnvVariable   `json:"env"`
	Volumes                 []VolumeMapping `json:"volumes"`
	DependsOn               []Dependency    `json:"dependsOn"`
	HealthCheck             *HealthCheck    `json:"healthCheck,omitempty"`
	Restart                 string          `json:"restart"`
	Command                 string          `json:"command,omitempty"`
	Entrypoint              string          `json:"entrypoint,omitempty"`
	User                    string          `json:"user,omitempty"`
	WorkingDir              string          `json:"workingDir,omitempty"`
	Resources               *ResourceLimits `json:"resources,omitempty"`
	Notes                   string          `json:"notes,omitempty"`
}

// Project represents a stored stack project
type Project struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Services    []DockerService `json:"services"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

// SecurityIssue represents an issue detected by the linter
type SecurityIssue struct {
	ID            string `json:"id"`
	ServiceID     string `json:"serviceId,omitempty"`
	Level         string `json:"level"` // "critical", "warning", "info", "success"
	Title         string `json:"title"`
	Message       string `json:"message"`
	FixSuggestion string `json:"fixSuggestion,omitempty"`
	AutoFixable   bool   `json:"autoFixable,omitempty"`
}

// DockerHubResult represents a search result from Docker Hub
type DockerHubResult struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	StarCount   int    `json:"starCount"`
	IsOfficial  bool   `json:"isOfficial"`
	PullCount   string `json:"pullCount"`
}

// SystemStatus represents local docker daemon status
type SystemStatus struct {
	DockerAvailable bool   `json:"dockerAvailable"`
	DockerVersion   string `json:"dockerVersion"`
	RunningStacks   int    `json:"runningStacks"`
	OS              string `json:"os"`
}
