import { DockerService, EnvVariable } from '../types/docker';

export interface WiringResult {
  updatedSource: DockerService;
  updatedTarget: DockerService;
  connectionDescription: string;
  relationType: 'database' | 'api' | 'proxy' | 'queue' | 'ai' | 'generic';
}

export function autoWireServices(
  sourceService: DockerService,
  targetService: DockerService
): WiringResult {
  const updatedSource = JSON.parse(JSON.stringify(sourceService)) as DockerService;
  const updatedTarget = JSON.parse(JSON.stringify(targetService)) as DockerService;

  // Ensure common network
  const commonNetwork = 'app-network';
  if (!updatedSource.networks.includes(commonNetwork)) updatedSource.networks.push(commonNetwork);
  if (!updatedTarget.networks.includes(commonNetwork)) updatedTarget.networks.push(commonNetwork);

  // Helper to add/update env var
  const setEnv = (service: DockerService, key: string, value: string, isSecret = false, desc = '') => {
    const existingIndex = service.env.findIndex(e => e.key === key);
    const newEnv: EnvVariable = {
      id: existingIndex >= 0 ? service.env[existingIndex].id : `env_${Date.now()}_${Math.random().toString(36).substr(2, 4)}`,
      key,
      value,
      isSecret,
      description: desc,
      autoGenerated: true
    };
    if (existingIndex >= 0) {
      service.env[existingIndex] = newEnv;
    } else {
      service.env.push(newEnv);
    }
  };

  const getTargetEnv = (key: string, fallback: string = ''): string => {
    const found = updatedTarget.env.find(e => e.key === key);
    return found ? found.value : fallback;
  };

  const addDependency = (service: DockerService, targetId: string, hasHealthCheck: boolean) => {
    const exists = service.dependsOn.some(d => d.serviceId === targetId);
    if (!exists) {
      service.dependsOn.push({
        serviceId: targetId,
        condition: hasHealthCheck ? 'service_healthy' : 'service_started'
      });
    }
  };

  let connectionDescription = `Connected ${updatedSource.displayName} to ${updatedTarget.displayName}`;
  let relationType: WiringResult['relationType'] = 'generic';

  // 1. BACKEND / APP -> DATABASE
  if (
    (updatedSource.category === 'backend' || updatedSource.category === 'custom') &&
    updatedTarget.category === 'database'
  ) {
    relationType = 'database';
    const targetName = updatedTarget.name;
    const hasHealth = !!(updatedTarget.healthCheck && updatedTarget.healthCheck.enabled);
    addDependency(updatedSource, updatedTarget.id, hasHealth);

    if (updatedTarget.image?.includes('postgres') || updatedTarget.name.includes('postgres')) {
      const dbUser = getTargetEnv('POSTGRES_USER', 'postgres');
      const dbPass = getTargetEnv('POSTGRES_PASSWORD', 'postgres_secure_pass_123');
      const dbName = getTargetEnv('POSTGRES_DB', 'app_db');
      const dbPort = updatedTarget.ports[0]?.containerPort || 5432;

      setEnv(updatedSource, 'DATABASE_URL', `postgresql://${dbUser}:${dbPass}@${targetName}:${dbPort}/${dbName}`, true, 'PostgreSQL Connection URL');
      setEnv(updatedSource, 'DB_HOST', targetName, false, 'Database hostname in docker network');
      setEnv(updatedSource, 'DB_PORT', String(dbPort), false, 'Database port');
      setEnv(updatedSource, 'DB_USER', dbUser, false, 'Database username');
      setEnv(updatedSource, 'DB_PASSWORD', dbPass, true, 'Database password');
      setEnv(updatedSource, 'DB_NAME', dbName, false, 'Database name');
      connectionDescription = `Configured PostgreSQL connection strings and health dependency`;
    } 
    else if (updatedTarget.image?.includes('mysql') || updatedTarget.image?.includes('mariadb') || updatedTarget.name.includes('mysql')) {
      const dbUser = getTargetEnv('MYSQL_USER', 'app_user');
      const dbPass = getTargetEnv('MYSQL_PASSWORD', 'app_pass_secret');
      const dbName = getTargetEnv('MYSQL_DATABASE', 'app_db');
      const dbPort = updatedTarget.ports[0]?.containerPort || 3306;

      setEnv(updatedSource, 'DATABASE_URL', `mysql://${dbUser}:${dbPass}@${targetName}:${dbPort}/${dbName}`, true, 'MySQL Connection URL');
      setEnv(updatedSource, 'DB_HOST', targetName, false, 'MySQL Host');
      setEnv(updatedSource, 'DB_PORT', String(dbPort), false, 'MySQL Port');
      setEnv(updatedSource, 'DB_USER', dbUser, false, 'MySQL User');
      setEnv(updatedSource, 'DB_PASSWORD', dbPass, true, 'MySQL Password');
      setEnv(updatedSource, 'DB_NAME', dbName, false, 'MySQL Database');
      connectionDescription = `Configured MySQL connection strings and health dependency`;
    }
    else if (updatedTarget.image?.includes('mongo') || updatedTarget.name.includes('mongo')) {
      const dbUser = getTargetEnv('MONGO_INITDB_ROOT_USERNAME', 'admin');
      const dbPass = getTargetEnv('MONGO_INITDB_ROOT_PASSWORD', 'admin_secret_pass');
      const dbName = getTargetEnv('MONGO_INITDB_DATABASE', 'app_db');
      const dbPort = updatedTarget.ports[0]?.containerPort || 27017;

      setEnv(updatedSource, 'MONGODB_URI', `mongodb://${dbUser}:${dbPass}@${targetName}:${dbPort}/${dbName}?authSource=admin`, true, 'MongoDB Connection URI');
      setEnv(updatedSource, 'MONGO_HOST', targetName, false, 'Mongo Host');
      setEnv(updatedSource, 'MONGO_PORT', String(dbPort), false, 'Mongo Port');
      connectionDescription = `Configured MongoDB connection URI`;
    }
    else if (updatedTarget.image?.includes('redis') || updatedTarget.name.includes('redis')) {
      const redisPort = updatedTarget.ports[0]?.containerPort || 6379;
      setEnv(updatedSource, 'REDIS_URL', `redis://:redis_secure_pass@${targetName}:${redisPort}/0`, true, 'Redis Cache URL');
      setEnv(updatedSource, 'REDIS_HOST', targetName, false, 'Redis host');
      setEnv(updatedSource, 'REDIS_PORT', String(redisPort), false, 'Redis port');
      connectionDescription = `Configured Redis cache connection`;
    }
  }

  // 2. FRONTEND -> BACKEND / API
  else if (updatedSource.category === 'frontend' && (updatedTarget.category === 'backend' || updatedTarget.category === 'custom')) {
    relationType = 'api';
    const targetPort = updatedTarget.ports[0]?.hostPort || updatedTarget.ports[0]?.containerPort || 8000;
    
    setEnv(updatedSource, 'VITE_API_URL', `http://localhost:${targetPort}`, false, 'Vite API Base URL');
    setEnv(updatedSource, 'NEXT_PUBLIC_API_URL', `http://localhost:${targetPort}`, false, 'Next.js Public API URL');
    setEnv(updatedSource, 'API_INTERNAL_URL', `http://${updatedTarget.name}:${updatedTarget.ports[0]?.containerPort || 8000}`, false, 'Docker internal API endpoint for SSR');
    
    addDependency(updatedSource, updatedTarget.id, false);
    connectionDescription = `Configured Frontend API base endpoints for ${updatedTarget.displayName}`;
  }

  // 3. GATEWAY / REVERSE PROXY -> ANY SERVICE
  else if (updatedSource.category === 'gateway') {
    relationType = 'proxy';
    addDependency(updatedSource, updatedTarget.id, false);
    const targetPort = updatedTarget.ports[0]?.containerPort || 80;
    setEnv(updatedSource, `UPSTREAM_${updatedTarget.name.toUpperCase()}`, `http://${updatedTarget.name}:${targetPort}`, false, `Upstream route for ${updatedTarget.displayName}`);
    connectionDescription = `Configured Gateway routing proxy to ${updatedTarget.displayName}`;
  }

  // 4. BACKEND / APP -> QUEUE / BROKER
  else if ((updatedSource.category === 'backend' || updatedSource.category === 'custom') && updatedTarget.category === 'queue') {
    relationType = 'queue';
    const hasHealth = !!(updatedTarget.healthCheck && updatedTarget.healthCheck.enabled);
    addDependency(updatedSource, updatedTarget.id, hasHealth);

    if (updatedTarget.name.includes('rabbit') || updatedTarget.image?.includes('rabbit')) {
      const user = getTargetEnv('RABBITMQ_DEFAULT_USER', 'rabbit_admin');
      const pass = getTargetEnv('RABBITMQ_DEFAULT_PASS', 'rabbit_pass_secure');
      setEnv(updatedSource, 'RABBITMQ_URL', `amqp://${user}:${pass}@${updatedTarget.name}:5672`, true, 'RabbitMQ AMQP connection string');
      connectionDescription = `Configured RabbitMQ broker URL`;
    } else if (updatedTarget.name.includes('kafka') || updatedTarget.image?.includes('kafka')) {
      setEnv(updatedSource, 'KAFKA_BROKERS', `${updatedTarget.name}:9092`, false, 'Kafka bootstrap broker list');
      connectionDescription = `Configured Kafka bootstrap broker address`;
    }
  }

  // 5. BACKEND / APP -> AI / VECTOR DB
  else if ((updatedSource.category === 'backend' || updatedSource.category === 'custom') && updatedTarget.category === 'ai') {
    relationType = 'ai';
    addDependency(updatedSource, updatedTarget.id, false);

    if (updatedTarget.name.includes('ollama') || updatedTarget.image?.includes('ollama')) {
      setEnv(updatedSource, 'OLLAMA_BASE_URL', `http://${updatedTarget.name}:11434`, false, 'Ollama Local LLM Endpoint');
      connectionDescription = `Configured Ollama local AI runtime endpoint`;
    } else if (updatedTarget.name.includes('qdrant') || updatedTarget.image?.includes('qdrant')) {
      setEnv(updatedSource, 'QDRANT_URL', `http://${updatedTarget.name}:6333`, false, 'Qdrant Vector Database REST endpoint');
      connectionDescription = `Configured Qdrant Vector search engine`;
    }
  }

  return {
    updatedSource,
    updatedTarget,
    connectionDescription,
    relationType
  };
}
