import { DockerService, EnvVariable } from '../types/docker';

export interface WiringResult {
  updatedSource: DockerService;
  updatedTarget: DockerService;
  connectionDescription: string;
  relationType: 'database' | 'api' | 'proxy' | 'queue' | 'ai' | 'generic';
}

export function autoWireServices(
  sourceService: DockerService,
  targetService: DockerService
): WiringResult {
  const updatedSource = JSON.parse(JSON.stringify(sourceService)) as DockerService;
  const updatedTarget = JSON.parse(JSON.stringify(targetService)) as DockerService;

  // Ensure common network
  const commonNetwork = 'app-network';
  if (!updatedSource.networks.includes(commonNetwork)) updatedSource.networks.push(commonNetwork);
  if (!updatedTarget.networks.includes(commonNetwork)) updatedTarget.networks.push(commonNetwork);

  // Helper to add/update env var
  const setEnv = (service: DockerService, key: string, value: string, isSecret = false, desc = '') => {
    const existingIndex = service.env.findIndex(e => e.key === key);
    const newEnv: EnvVariable = {
      id: existingIndex >= 0 ? service.env[existingIndex].id : `env_${Date.now()}_${Math.random().toString(36).substr(2, 4)}`,
      key,
      value,
      isSecret,
      description: desc,
      autoGenerated: true
    };
    if (existingIndex >= 0) {
      service.env[existingIndex] = newEnv;
    } else {
      service.env.push(newEnv);
    }
  };

<<<<<<< HEAD
  const getTargetEnv = (key: string, fallback: string = ''): string => {
    const found = updatedTarget.env.find(e => e.key === key);
    return found ? found.value : fallback;
  };

  const addDependency = (service: DockerService, targetId: string, hasHealthCheck: boolean) => {
    const exists = service.dependsOn.some(d => d.serviceId === targetId);
    if (!exists) {
      service.dependsOn.push({
        serviceId: targetId,
        condition: hasHealthCheck ? 'service_healthy' : 'service_started'
=======
  const getEnvValue = (service: DockerService, key: string, fallback: string = ''): string => {
    const found = service.env.find(e => e.key === key);
    return found ? found.value : fallback;
  };

  const addDependency = (consumer: DockerService, provider: DockerService) => {
    const hasHealth = !!(provider.healthCheck && provider.healthCheck.enabled);
    const exists = consumer.dependsOn.some(d => d.serviceId === provider.id);
    if (!exists) {
      consumer.dependsOn.push({
        serviceId: provider.id,
        condition: hasHealth ? 'service_healthy' : 'service_started'
>>>>>>> bf34f7e (feat(frontend): implement visual ReactFlow canvas, magnetic glowing handles, bidirectional auto-wiring & live code generators)
      });
    }
  };

  let connectionDescription = `Connected ${updatedSource.displayName} to ${updatedTarget.displayName}`;
  let relationType: WiringResult['relationType'] = 'generic';

<<<<<<< HEAD
  // 1. BACKEND / APP -> DATABASE
  if (
    (updatedSource.category === 'backend' || updatedSource.category === 'custom') &&
    updatedTarget.category === 'database'
  ) {
    relationType = 'database';
    const targetName = updatedTarget.name;
    const hasHealth = !!(updatedTarget.healthCheck && updatedTarget.healthCheck.enabled);
    addDependency(updatedSource, updatedTarget.id, hasHealth);

    if (updatedTarget.image?.includes('postgres') || updatedTarget.name.includes('postgres')) {
      const dbUser = getTargetEnv('POSTGRES_USER', 'postgres');
      const dbPass = getTargetEnv('POSTGRES_PASSWORD', 'postgres_secure_pass_123');
      const dbName = getTargetEnv('POSTGRES_DB', 'app_db');
      const dbPort = updatedTarget.ports[0]?.containerPort || 5432;

      setEnv(updatedSource, 'DATABASE_URL', `postgresql://${dbUser}:${dbPass}@${targetName}:${dbPort}/${dbName}`, true, 'PostgreSQL Connection URL');
      setEnv(updatedSource, 'DB_HOST', targetName, false, 'Database hostname in docker network');
      setEnv(updatedSource, 'DB_PORT', String(dbPort), false, 'Database port');
      setEnv(updatedSource, 'DB_USER', dbUser, false, 'Database username');
      setEnv(updatedSource, 'DB_PASSWORD', dbPass, true, 'Database password');
      setEnv(updatedSource, 'DB_NAME', dbName, false, 'Database name');
      connectionDescription = `Configured PostgreSQL connection strings and health dependency`;
    } 
    else if (updatedTarget.image?.includes('mysql') || updatedTarget.image?.includes('mariadb') || updatedTarget.name.includes('mysql')) {
      const dbUser = getTargetEnv('MYSQL_USER', 'app_user');
      const dbPass = getTargetEnv('MYSQL_PASSWORD', 'app_pass_secret');
      const dbName = getTargetEnv('MYSQL_DATABASE', 'app_db');
      const dbPort = updatedTarget.ports[0]?.containerPort || 3306;

      setEnv(updatedSource, 'DATABASE_URL', `mysql://${dbUser}:${dbPass}@${targetName}:${dbPort}/${dbName}`, true, 'MySQL Connection URL');
      setEnv(updatedSource, 'DB_HOST', targetName, false, 'MySQL Host');
      setEnv(updatedSource, 'DB_PORT', String(dbPort), false, 'MySQL Port');
      setEnv(updatedSource, 'DB_USER', dbUser, false, 'MySQL User');
      setEnv(updatedSource, 'DB_PASSWORD', dbPass, true, 'MySQL Password');
      setEnv(updatedSource, 'DB_NAME', dbName, false, 'MySQL Database');
      connectionDescription = `Configured MySQL connection strings and health dependency`;
    }
    else if (updatedTarget.image?.includes('mongo') || updatedTarget.name.includes('mongo')) {
      const dbUser = getTargetEnv('MONGO_INITDB_ROOT_USERNAME', 'admin');
      const dbPass = getTargetEnv('MONGO_INITDB_ROOT_PASSWORD', 'admin_secret_pass');
      const dbName = getTargetEnv('MONGO_INITDB_DATABASE', 'app_db');
      const dbPort = updatedTarget.ports[0]?.containerPort || 27017;

      setEnv(updatedSource, 'MONGODB_URI', `mongodb://${dbUser}:${dbPass}@${targetName}:${dbPort}/${dbName}?authSource=admin`, true, 'MongoDB Connection URI');
      setEnv(updatedSource, 'MONGO_HOST', targetName, false, 'Mongo Host');
      setEnv(updatedSource, 'MONGO_PORT', String(dbPort), false, 'Mongo Port');
      connectionDescription = `Configured MongoDB connection URI`;
    }
    else if (updatedTarget.image?.includes('redis') || updatedTarget.name.includes('redis')) {
      const redisPort = updatedTarget.ports[0]?.containerPort || 6379;
      setEnv(updatedSource, 'REDIS_URL', `redis://:redis_secure_pass@${targetName}:${redisPort}/0`, true, 'Redis Cache URL');
      setEnv(updatedSource, 'REDIS_HOST', targetName, false, 'Redis host');
      setEnv(updatedSource, 'REDIS_PORT', String(redisPort), false, 'Redis port');
      connectionDescription = `Configured Redis cache connection`;
    }
  }

  // 2. FRONTEND -> BACKEND / API
  else if (updatedSource.category === 'frontend' && (updatedTarget.category === 'backend' || updatedTarget.category === 'custom')) {
    relationType = 'api';
    const targetPort = updatedTarget.ports[0]?.hostPort || updatedTarget.ports[0]?.containerPort || 8000;
    
    setEnv(updatedSource, 'VITE_API_URL', `http://localhost:${targetPort}`, false, 'Vite API Base URL');
    setEnv(updatedSource, 'NEXT_PUBLIC_API_URL', `http://localhost:${targetPort}`, false, 'Next.js Public API URL');
    setEnv(updatedSource, 'API_INTERNAL_URL', `http://${updatedTarget.name}:${updatedTarget.ports[0]?.containerPort || 8000}`, false, 'Docker internal API endpoint for SSR');
    
    addDependency(updatedSource, updatedTarget.id, false);
    connectionDescription = `Configured Frontend API base endpoints for ${updatedTarget.displayName}`;
  }

  // 3. GATEWAY / REVERSE PROXY -> ANY SERVICE
  else if (updatedSource.category === 'gateway') {
    relationType = 'proxy';
    addDependency(updatedSource, updatedTarget.id, false);
    const targetPort = updatedTarget.ports[0]?.containerPort || 80;
    setEnv(updatedSource, `UPSTREAM_${updatedTarget.name.toUpperCase()}`, `http://${updatedTarget.name}:${targetPort}`, false, `Upstream route for ${updatedTarget.displayName}`);
    connectionDescription = `Configured Gateway routing proxy to ${updatedTarget.displayName}`;
  }

  // 4. BACKEND / APP -> QUEUE / BROKER
  else if ((updatedSource.category === 'backend' || updatedSource.category === 'custom') && updatedTarget.category === 'queue') {
    relationType = 'queue';
    const hasHealth = !!(updatedTarget.healthCheck && updatedTarget.healthCheck.enabled);
    addDependency(updatedSource, updatedTarget.id, hasHealth);

    if (updatedTarget.name.includes('rabbit') || updatedTarget.image?.includes('rabbit')) {
      const user = getTargetEnv('RABBITMQ_DEFAULT_USER', 'rabbit_admin');
      const pass = getTargetEnv('RABBITMQ_DEFAULT_PASS', 'rabbit_pass_secure');
      setEnv(updatedSource, 'RABBITMQ_URL', `amqp://${user}:${pass}@${updatedTarget.name}:5672`, true, 'RabbitMQ AMQP connection string');
      connectionDescription = `Configured RabbitMQ broker URL`;
    } else if (updatedTarget.name.includes('kafka') || updatedTarget.image?.includes('kafka')) {
      setEnv(updatedSource, 'KAFKA_BROKERS', `${updatedTarget.name}:9092`, false, 'Kafka bootstrap broker list');
      connectionDescription = `Configured Kafka bootstrap broker address`;
    }
  }

  // 5. BACKEND / APP -> AI / VECTOR DB
  else if ((updatedSource.category === 'backend' || updatedSource.category === 'custom') && updatedTarget.category === 'ai') {
    relationType = 'ai';
    addDependency(updatedSource, updatedTarget.id, false);

    if (updatedTarget.name.includes('ollama') || updatedTarget.image?.includes('ollama')) {
      setEnv(updatedSource, 'OLLAMA_BASE_URL', `http://${updatedTarget.name}:11434`, false, 'Ollama Local LLM Endpoint');
      connectionDescription = `Configured Ollama local AI runtime endpoint`;
    } else if (updatedTarget.name.includes('qdrant') || updatedTarget.image?.includes('qdrant')) {
      setEnv(updatedSource, 'QDRANT_URL', `http://${updatedTarget.name}:6333`, false, 'Qdrant Vector Database REST endpoint');
      connectionDescription = `Configured Qdrant Vector search engine`;
    }
  }

=======
  // Identify Roles regardless of drag direction (Source <-> Target)
  const isDB = (s: DockerService) => s.category === 'database';
  const isBackend = (s: DockerService) => s.category === 'backend' || s.category === 'custom';
  const isFrontend = (s: DockerService) => s.category === 'frontend';
  const isGateway = (s: DockerService) => s.category === 'gateway';
  const isQueue = (s: DockerService) => s.category === 'queue';
  const isAI = (s: DockerService) => s.category === 'ai';

  // 1. BACKEND <-> DATABASE (Any direction)
  if ((isBackend(updatedSource) && isDB(updatedTarget)) || (isDB(updatedSource) && isBackend(updatedTarget))) {
    const app = isBackend(updatedSource) ? updatedSource : updatedTarget;
    const db = isDB(updatedSource) ? updatedSource : updatedTarget;
    relationType = 'database';

    addDependency(app, db);

    if (db.image?.includes('postgres') || db.name.includes('postgres')) {
      const dbUser = getEnvValue(db, 'POSTGRES_USER', 'postgres');
      const dbPass = getEnvValue(db, 'POSTGRES_PASSWORD', 'postgres_secure_pass_123');
      const dbName = getEnvValue(db, 'POSTGRES_DB', 'app_db');
      const dbPort = db.ports[0]?.containerPort || 5432;

      setEnv(app, 'DATABASE_URL', `postgresql://${dbUser}:${dbPass}@${db.name}:${dbPort}/${dbName}`, true, 'PostgreSQL Connection URL');
      setEnv(app, 'DB_HOST', db.name, false, 'Database hostname in docker network');
      setEnv(app, 'DB_PORT', String(dbPort), false, 'Database port');
      setEnv(app, 'DB_USER', dbUser, false, 'Database username');
      setEnv(app, 'DB_PASSWORD', dbPass, true, 'Database password');
      setEnv(app, 'DB_NAME', dbName, false, 'Database name');
      connectionDescription = `Configured PostgreSQL connection strings for ${app.displayName}`;
    } 
    else if (db.image?.includes('mysql') || db.image?.includes('mariadb') || db.name.includes('mysql')) {
      const dbUser = getEnvValue(db, 'MYSQL_USER', 'app_user');
      const dbPass = getEnvValue(db, 'MYSQL_PASSWORD', 'app_pass_secret');
      const dbName = getEnvValue(db, 'MYSQL_DATABASE', 'app_db');
      const dbPort = db.ports[0]?.containerPort || 3306;

      setEnv(app, 'DATABASE_URL', `mysql://${dbUser}:${dbPass}@${db.name}:${dbPort}/${dbName}`, true, 'MySQL Connection URL');
      setEnv(app, 'DB_HOST', db.name, false, 'MySQL Host');
      setEnv(app, 'DB_PORT', String(dbPort), false, 'MySQL Port');
      setEnv(app, 'DB_USER', dbUser, false, 'MySQL User');
      setEnv(app, 'DB_PASSWORD', dbPass, true, 'MySQL Password');
      setEnv(app, 'DB_NAME', dbName, false, 'MySQL Database');
      connectionDescription = `Configured MySQL connection strings for ${app.displayName}`;
    }
    else if (db.image?.includes('mongo') || db.name.includes('mongo')) {
      const dbUser = getEnvValue(db, 'MONGO_INITDB_ROOT_USERNAME', 'admin');
      const dbPass = getEnvValue(db, 'MONGO_INITDB_ROOT_PASSWORD', 'admin_secret_pass');
      const dbName = getEnvValue(db, 'MONGO_INITDB_DATABASE', 'app_db');
      const dbPort = db.ports[0]?.containerPort || 27017;

      setEnv(app, 'MONGODB_URI', `mongodb://${dbUser}:${dbPass}@${db.name}:${dbPort}/${dbName}?authSource=admin`, true, 'MongoDB Connection URI');
      setEnv(app, 'MONGO_HOST', db.name, false, 'Mongo Host');
      setEnv(app, 'MONGO_PORT', String(dbPort), false, 'Mongo Port');
      connectionDescription = `Configured MongoDB connection URI for ${app.displayName}`;
    }
    else if (db.image?.includes('redis') || db.name.includes('redis')) {
      const redisPort = db.ports[0]?.containerPort || 6379;
      setEnv(app, 'REDIS_URL', `redis://:redis_secure_pass@${db.name}:${redisPort}/0`, true, 'Redis Cache URL');
      setEnv(app, 'REDIS_HOST', db.name, false, 'Redis host');
      setEnv(app, 'REDIS_PORT', String(redisPort), false, 'Redis port');
      connectionDescription = `Configured Redis cache connection for ${app.displayName}`;
    }
  }

  // 2. FRONTEND <-> BACKEND / API (Any direction)
  else if ((isFrontend(updatedSource) && isBackend(updatedTarget)) || (isBackend(updatedSource) && isFrontend(updatedTarget))) {
    const front = isFrontend(updatedSource) ? updatedSource : updatedTarget;
    const back = isBackend(updatedSource) ? updatedSource : updatedTarget;
    relationType = 'api';

    const targetPort = back.ports[0]?.hostPort || back.ports[0]?.containerPort || 8000;
    
    setEnv(front, 'VITE_API_URL', `http://localhost:${targetPort}`, false, 'Vite API Base URL');
    setEnv(front, 'NEXT_PUBLIC_API_URL', `http://localhost:${targetPort}`, false, 'Next.js Public API URL');
    setEnv(front, 'API_INTERNAL_URL', `http://${back.name}:${back.ports[0]?.containerPort || 8000}`, false, 'Docker internal API endpoint for SSR');
    
    addDependency(front, back);
    connectionDescription = `Configured API endpoints from ${front.displayName} to ${back.displayName}`;
  }

  // 3. GATEWAY <-> ANY SERVICE
  else if (isGateway(updatedSource) || isGateway(updatedTarget)) {
    const gw = isGateway(updatedSource) ? updatedSource : updatedTarget;
    const target = isGateway(updatedSource) ? updatedTarget : updatedSource;
    relationType = 'proxy';

    addDependency(gw, target);
    const targetPort = target.ports[0]?.containerPort || 80;
    setEnv(gw, `UPSTREAM_${target.name.toUpperCase()}`, `http://${target.name}:${targetPort}`, false, `Upstream route for ${target.displayName}`);
    connectionDescription = `Configured Gateway routing proxy to ${target.displayName}`;
  }

  // 4. BACKEND <-> QUEUE / BROKER
  else if ((isBackend(updatedSource) && isQueue(updatedTarget)) || (isQueue(updatedSource) && isBackend(updatedTarget))) {
    const app = isBackend(updatedSource) ? updatedSource : updatedTarget;
    const q = isQueue(updatedSource) ? updatedSource : updatedTarget;
    relationType = 'queue';

    addDependency(app, q);

    if (q.name.includes('rabbit') || q.image?.includes('rabbit')) {
      const user = getEnvValue(q, 'RABBITMQ_DEFAULT_USER', 'rabbit_admin');
      const pass = getEnvValue(q, 'RABBITMQ_DEFAULT_PASS', 'rabbit_pass_secure');
      setEnv(app, 'RABBITMQ_URL', `amqp://${user}:${pass}@${q.name}:5672`, true, 'RabbitMQ AMQP connection string');
      connectionDescription = `Configured RabbitMQ broker URL for ${app.displayName}`;
    } else if (q.name.includes('kafka') || q.image?.includes('kafka')) {
      setEnv(app, 'KAFKA_BROKERS', `${q.name}:9092`, false, 'Kafka bootstrap broker list');
      connectionDescription = `Configured Kafka bootstrap broker address for ${app.displayName}`;
    }
  }

  // 5. BACKEND <-> AI / VECTOR DB
  else if ((isBackend(updatedSource) && isAI(updatedTarget)) || (isAI(updatedSource) && isBackend(updatedTarget))) {
    const app = isBackend(updatedSource) ? updatedSource : updatedTarget;
    const ai = isAI(updatedSource) ? updatedSource : updatedTarget;
    relationType = 'ai';

    addDependency(app, ai);

    if (ai.name.includes('ollama') || ai.image?.includes('ollama')) {
      setEnv(app, 'OLLAMA_BASE_URL', `http://${ai.name}:11434`, false, 'Ollama Local LLM Endpoint');
      connectionDescription = `Configured Ollama local AI runtime for ${app.displayName}`;
    } else if (ai.name.includes('qdrant') || ai.image?.includes('qdrant')) {
      setEnv(app, 'QDRANT_URL', `http://${ai.name}:6333`, false, 'Qdrant Vector Database REST endpoint');
      connectionDescription = `Configured Qdrant Vector search engine for ${app.displayName}`;
    }
  }

  // 6. GENERIC FALLBACK (Any other 2 services connected by user)
  else {
    addDependency(updatedSource, updatedTarget);
    connectionDescription = `Linked ${updatedSource.displayName} with ${updatedTarget.displayName}`;
  }

>>>>>>> bf34f7e (feat(frontend): implement visual ReactFlow canvas, magnetic glowing handles, bidirectional auto-wiring & live code generators)
  return {
    updatedSource,
    updatedTarget,
    connectionDescription,
    relationType
  };
}
