import { DockerService, DockerNetwork, DockerVolume } from '../types/docker';

export interface ComposeGeneratorOptions {
  projectName?: string;
  useEnvFile?: boolean;
  indent?: number;
}

export function generateDockerComposeYaml(
  services: DockerService[],
  networks: DockerNetwork[] = [{ name: 'app-network', driver: 'bridge' }],
  volumes: DockerVolume[] = [],
  options: ComposeGeneratorOptions = { useEnvFile: true }
): string {
  if (services.length === 0) {
    return `# ==========================================
# DockCraft - Visual Docker & Infrastructure Studio
# Add services from the left palette to generate docker-compose.yml
# ==========================================
services: {}
`;
  }

  const collectedVolumeNames = new Set<string>();
  volumes.forEach(v => collectedVolumeNames.add(v.name));
  services.forEach(s => {
    s.volumes.forEach(v => {
      if (v.type === 'volume' && v.hostPath && !v.hostPath.startsWith('.') && !v.hostPath.startsWith('/')) {
        collectedVolumeNames.add(v.hostPath);
      }
    });
  });

  const collectedNetworkNames = new Set<string>();
  networks.forEach(n => collectedNetworkNames.add(n.name));
  services.forEach(s => {
    s.networks.forEach(n => collectedNetworkNames.add(n));
  });

  let yaml = `# ==============================================================================
# Generated by DockCraft Studio (https://github.com/dockcraft)
# Architecture: ${services.map(s => s.displayName).join(', ')}
# Generated at: ${new Date().toISOString().split('T')[0]}
# ==============================================================================

services:
`;

  services.forEach(service => {
    yaml += `  ${service.name}:\n`;
    yaml += `    container_name: ${service.name}\n`;

    if (service.isCustomBuild) {
      yaml += `    build:\n`;
      yaml += `      context: ${service.buildContext || '.'}\n`;
      if (service.dockerfilePath) {
        yaml += `      dockerfile: ${service.dockerfilePath.replace(`${service.buildContext || '.'}/`, '')}\n`;
      }
    } else {
      const tag = service.tag || 'latest';
      yaml += `    image: ${service.image}:${tag}\n`;
    }

    if (service.restart) {
      yaml += `    restart: ${service.restart}\n`;
    }

    if (service.command && service.command.trim()) {
      yaml += `    command: ${service.command}\n`;
    }

    if (service.entrypoint && service.entrypoint.trim()) {
      yaml += `    entrypoint: ${service.entrypoint}\n`;
    }

    if (service.user && service.user.trim()) {
      yaml += `    user: "${service.user}"\n`;
    }

    if (service.ports && service.ports.length > 0) {
      yaml += `    ports:\n`;
      service.ports.forEach(p => {
        const proto = p.protocol && p.protocol !== 'tcp' ? `/${p.protocol}` : '';
        const desc = p.description ? ` # ${p.description}` : '';
        yaml += `      - "${p.hostPort}:${p.containerPort}${proto}"${desc}\n`;
      });
    }

    if (service.env && service.env.length > 0) {
      yaml += `    environment:\n`;
      service.env.forEach(e => {
        if (options.useEnvFile && e.isSecret) {
          yaml += `      - ${e.key}=\${${e.key}:-${e.value}}\n`;
        } else {
          yaml += `      - ${e.key}=${e.value}\n`;
        }
      });
    }

    if (service.volumes && service.volumes.length > 0) {
      yaml += `    volumes:\n`;
      service.volumes.forEach(v => {
        const ro = v.readOnly ? ':ro' : '';
        const desc = v.description ? ` # ${v.description}` : '';
        yaml += `      - ${v.hostPath}:${v.containerPath}${ro}${desc}\n`;
      });
    }

    if (service.dependsOn && service.dependsOn.length > 0) {
      yaml += `    depends_on:\n`;
      service.dependsOn.forEach(dep => {
        const target = services.find(s => s.id === dep.serviceId);
        const targetName = target ? target.name : dep.serviceId;
        yaml += `      ${targetName}:\n`;
        yaml += `        condition: ${dep.condition || 'service_started'}\n`;
      });
    }

    if (service.healthCheck && service.healthCheck.enabled && service.healthCheck.test) {
      yaml += `    healthcheck:\n`;
      yaml += `      test: ["CMD-SHELL", "${service.healthCheck.test}"]\n`;
      yaml += `      interval: ${service.healthCheck.interval || '10s'}\n`;
      yaml += `      timeout: ${service.healthCheck.timeout || '5s'}\n`;
      yaml += `      retries: ${service.healthCheck.retries || 5}\n`;
      if (service.healthCheck.startPeriod) {
        yaml += `      start_period: ${service.healthCheck.startPeriod}\n`;
      }
    }

    if (service.networks && service.networks.length > 0) {
      yaml += `    networks:\n`;
      service.networks.forEach(n => {
        yaml += `      - ${n}\n`;
      });
    }

    if (service.resources && (service.resources.cpus || service.resources.memory)) {
      yaml += `    deploy:\n`;
      yaml += `      resources:\n`;
      yaml += `        limits:\n`;
      if (service.resources.cpus) yaml += `          cpus: '${service.resources.cpus}'\n`;
      if (service.resources.memory) yaml += `          memory: ${service.resources.memory}\n`;
    }

    yaml += `\n`;
  });

  if (collectedNetworkNames.size > 0) {
    yaml += `networks:\n`;
    collectedNetworkNames.forEach(netName => {
      yaml += `  ${netName}:\n`;
      yaml += `    driver: bridge\n`;
    });
    yaml += `\n`;
  }

  if (collectedVolumeNames.size > 0) {
    yaml += `volumes:\n`;
    collectedVolumeNames.forEach(volName => {
      yaml += `  ${volName}:\n`;
      yaml += `    driver: local\n`;
    });
  }

  return yaml;
}
