import { DockerService } from '../types/docker';
import { hardenAllStackSecrets } from './secretsVault';

export interface ProductionBundleOptions {
  domainName: string;
  enableSSL: boolean;
  sslEmail: string;
  enableCICD: boolean;
  enableDBBackupCron: boolean;
}

export interface GeneratedProductionBundle {
  files: {
    path: string;
    content: string;
    description: string;
  }[];
  composeProdYaml: string;
  nginxProdConf: string;
  githubActionsYaml: string;
  deploySh: string;
  deployPs1: string;
  makefile: string;
  envProduction: string;
}

export function generateProductionBundle(
  services: DockerService[],
  projectName: string,
  options: ProductionBundleOptions = {
    domainName: 'app.example.com',
    enableSSL: true,
    sslEmail: 'admin@example.com',
    enableCICD: true,
    enableDBBackupCron: true,
  }
): GeneratedProductionBundle {
  const { domainName, enableSSL, sslEmail, enableCICD } = options;
  const cleanDomain = domainName.trim() || 'app.example.com';
  const cleanEmail = sslEmail.trim() || 'admin@example.com';

  // 1. Harden all secrets
  const { services: hardenedServices } = hardenAllStackSecrets(services);

  // 2. Generate docker-compose.prod.yml
  const composeProdYaml = generateProductionComposeYaml(hardenedServices, cleanDomain, enableSSL);

  // 3. Generate nginx/nginx.prod.conf
  const nginxProdConf = generateProductionNginxConf(hardenedServices, cleanDomain, enableSSL);

  // 4. Generate .github/workflows/deploy.yml
  const githubActionsYaml = generateGitHubActionsWorkflow(cleanDomain);

  // 5. Generate deploy-prod.sh & deploy-prod.ps1
  const deploySh = generateDeployScriptSh(cleanDomain, enableSSL, cleanEmail);
  const deployPs1 = generateDeployScriptPs1(cleanDomain);

  // 6. Generate Makefile
  const makefile = generateProductionMakefile();

  // 7. Generate .env.production
  const envProduction = generateProductionEnvFile(hardenedServices);

  const files = [
    {
      path: 'docker-compose.prod.yml',
      content: composeProdYaml,
      description: 'Production-Hardened Multi-Container Orchestration',
    },
    {
      path: 'nginx/nginx.prod.conf',
      content: nginxProdConf,
      description: 'Zero-Trust High-Performance Reverse Proxy with SSL',
    },
    {
      path: '.env.production',
      content: envProduction,
      description: 'Production Cryptographically Hardened Environment Secrets',
    },
    {
      path: 'deploy-prod.sh',
      content: deploySh,
      description: '1-Click Zero-Code Linux/VPS Production Deployment Script',
    },
    {
      path: 'deploy-prod.ps1',
      content: deployPs1,
      description: '1-Click Windows Production Deployment Script',
    },
    {
      path: 'Makefile',
      content: makefile,
      description: 'Ops & Maintenance Commands (up, down, logs, backup)',
    },
  ];

  if (enableCICD) {
    files.push({
      path: '.github/workflows/deploy.yml',
      content: githubActionsYaml,
      description: 'Automated CI/CD Test, Build & SSH Zero-Downtime Deploy Pipeline',
    });
  }

  return {
    files,
    composeProdYaml,
    nginxProdConf,
    githubActionsYaml,
    deploySh,
    deployPs1,
    makefile,
    envProduction,
  };
}

function generateProductionComposeYaml(services: DockerService[], domain: string, enableSSL: boolean): string {
  const lines: string[] = [
    '# ==============================================================================',
    '# 🚀 PRODUCTION-HARDENED DOCKER COMPOSE ORCHESTRATION',
    `# 🌐 Target Domain: ${domain}`,
    '# 🔒 Generated by DockCraft Studio — Zero-Code Production Pack',
    '# ==============================================================================',
    'version: "3.8"',
    '',
    'services:',
  ];

  // Add Reverse Proxy Gateway
  lines.push('  # 🛡️ High-Performance SSL Reverse Proxy & Gateway');
  lines.push('  gateway:');
  lines.push('    image: nginx:alpine');
  lines.push('    container_name: prod_nginx_gateway');
  lines.push('    restart: always');
  lines.push('    ports:');
  lines.push('      - "80:80"');
  if (enableSSL) {
    lines.push('      - "443:443"');
  }
  lines.push('    volumes:');
  lines.push('      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro');
  lines.push('      - certbot_etc:/etc/letsencrypt:ro');
  lines.push('      - certbot_var:/var/lib/letsencrypt:ro');
  lines.push('      - ./certbot/www:/var/www/certbot:ro');
  lines.push('    networks:');
  lines.push('      - public_net');
  lines.push('      - internal_net');
  lines.push('    logging:');
  lines.push('      driver: "json-file"');
  lines.push('      options:');
  lines.push('        max-size: "10m"');
  lines.push('        max-file: "3"');
  lines.push('    deploy:');
  lines.push('      resources:');
  lines.push('        limits:');
  lines.push('          cpus: "0.50"');
  lines.push('          memory: 256M');
  lines.push('');

  // Add Certbot for SSL auto-renewal if SSL enabled
  if (enableSSL) {
    lines.push('  # 🔒 Automatic Let\'s Encrypt SSL/TLS Certificate Manager');
    lines.push('  certbot:');
    lines.push('    image: certbot/certbot:latest');
    lines.push('    container_name: prod_certbot');
    lines.push('    volumes:');
    lines.push('      - certbot_etc:/etc/letsencrypt');
    lines.push('      - certbot_var:/var/lib/letsencrypt');
    lines.push('      - ./certbot/www:/var/www/certbot');
    lines.push('    entrypoint: "/bin/sh -c \'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;\'"');
    lines.push('    networks:');
    lines.push('      - public_net');
    lines.push('');
  }

  // Add individual services
  services.forEach((s) => {
    lines.push(`  # --- [${s.category.toUpperCase()}] ${s.displayName} ---`);
    lines.push(`  ${s.name}:`);

    if (s.isCustomBuild) {
      lines.push('    build:');
      lines.push(`      context: ${s.buildContext || '.'}`);
      lines.push(`      dockerfile: ${s.dockerfilePath || 'Dockerfile'}`);
    } else {
      lines.push(`    image: ${s.image}:${s.tag || 'latest'}`);
    }

    lines.push(`    container_name: prod_${s.name}`);
    lines.push('    restart: always');
    lines.push('    env_file:');
    lines.push('      - .env.production');

    // Healthcheck
    if (s.healthCheck?.enabled) {
      lines.push('    healthcheck:');
      lines.push(`      test: ["CMD-SHELL", "${s.healthCheck.test}"]`);
      lines.push(`      interval: ${s.healthCheck.interval || '15s'}`);
      lines.push(`      timeout: ${s.healthCheck.timeout || '5s'}`);
      lines.push(`      retries: ${s.healthCheck.retries || 3}`);
      lines.push(`      start_period: ${s.healthCheck.startPeriod || '20s'}`);
    }

    // Volumes
    if (s.volumes.length > 0) {
      lines.push('    volumes:');
      s.volumes.forEach((v) => {
        lines.push(`      - ${v.hostPath}:${v.containerPath}`);
      });
    }

    // Depends on
    if (s.dependsOn.length > 0) {
      lines.push('    depends_on:');
      s.dependsOn.forEach((dep) => {
        const target = services.find((t) => t.id === dep.serviceId);
        if (target) {
          lines.push(`      - ${target.name}`);
        }
      });
    }

    // Isolated Networks
    lines.push('    networks:');
    if (s.category === 'frontend' || s.category === 'gateway') {
      lines.push('      - public_net');
    }
    lines.push('      - internal_net');

    // Resource Limits
    lines.push('    deploy:');
    lines.push('      resources:');
    lines.push('        limits:');
    lines.push(`          cpus: "${s.resources?.cpus || '1.0'}"`);
    lines.push(`          memory: ${s.resources?.memory || '512M'}`);

    // Log Rotation
    lines.push('    logging:');
    lines.push('      driver: "json-file"');
    lines.push('      options:');
    lines.push('        max-size: "20m"');
    lines.push('        max-file: "5"');
    lines.push('');
  });

  // Networks definition
  lines.push('networks:');
  lines.push('  public_net:');
  lines.push('    driver: bridge');
  lines.push('  internal_net:');
  lines.push('    internal: false');
  lines.push('');

  // Volumes definition
  lines.push('volumes:');
  lines.push('  certbot_etc:');
  lines.push('  certbot_var:');
  services.forEach((s) => {
    s.volumes.forEach((v) => {
      if (v.type === 'volume') {
        lines.push(`  ${v.hostPath}:`);
      }
    });
  });

  return lines.join('\n');
}

function generateProductionNginxConf(services: DockerService[], domain: string, enableSSL: boolean): string {
  const frontends = services.filter((s) => s.category === 'frontend');
  const backends = services.filter((s) => s.category === 'backend');

  const primaryFront = frontends[0];
  const primaryBack = backends[0];

  const frontPort = primaryFront?.ports[0]?.containerPort || 80;
  const backPort = primaryBack?.ports[0]?.containerPort || 8000;

  return `user nginx;
worker_processes auto;
pid /var/run/nginx.pid;
error_log /var/log/nginx/error.log warn;

events {
    worker_connections 2048;
    use epoll;
    multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Logging
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;

    # Performance
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    server_tokens off;

    # Gzip Compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

    # Rate Limiting Zone
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=50r/s;

    # Upstream Backends
    ${primaryFront ? `upstream frontend_cluster {\n        server ${primaryFront.name}:${frontPort};\n        keepalive 32;\n    }` : ''}
    ${primaryBack ? `upstream api_cluster {\n        server ${primaryBack.name}:${backPort};\n        keepalive 32;\n    }` : ''}

    # 1. HTTP Server (Port 80)
    server {
        listen 80;
        listen [::]:80;
        server_name ${domain} www.${domain};

        # Let's Encrypt challenge verification
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        ${enableSSL ? `location / {\n            return 301 https://$host$request_uri;\n        }` : `
        location /api/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://api_cluster;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://frontend_cluster;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }`}
    }

    ${enableSSL ? `
    # 2. HTTPS Server (Port 443 with SSL/TLS)
    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name ${domain} www.${domain};

        # SSL Certificates
        ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;

        # Modern SSL Settings
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;
        ssl_session_tickets off;

        # Security Headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

        # API Reverse Proxy with Rate Limiting
        location /api/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://api_cluster;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_read_timeout 90s;
        }

        # WebSocket Streaming Endpoint
        location /ws/ {
            proxy_pass http://api_cluster;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 86400s;
        }

        # Frontend SPA / SSR Reverse Proxy
        location / {
            proxy_pass http://frontend_cluster;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }` : ''}
}
`;
}

function generateGitHubActionsWorkflow(domain: string): string {
  return `name: 🚀 Production CI/CD Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-audit:
    name: 🧪 Run Security & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Compose Configuration
        run: docker compose -f docker-compose.prod.yml config

  deploy-production:
    name: 🌐 Deploy to Production Server
    needs: test-and-audit
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: \${{ secrets.PROD_SERVER_HOST }}
          username: \${{ secrets.PROD_SERVER_USER }}
          key: \${{ secrets.PROD_SERVER_SSH_KEY }}
          port: \${{ secrets.PROD_SERVER_PORT || 22 }}
          script: |
            cd /opt/app
            git pull origin main
            docker compose -f docker-compose.prod.yml pull || true
            docker compose -f docker-compose.prod.yml up -d --build --remove-orphans
            docker image prune -f
            echo "✅ Deployment completed on https://${domain}"
`;
}

function generateDeployScriptSh(domain: string, enableSSL: boolean, email: string): string {
  return `#!/bin/bash
# ==============================================================================
# 🚀 ZERO-CODE PRODUCTION DEPLOYMENT SCRIPT
# Target Domain: ${domain}
# ==============================================================================

set -e

echo "=================================================="
echo "  🚀 Starting Production Deployment (${domain})"
echo "=================================================="

# 1. Check Docker & Docker Compose
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed! Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker $USER
fi

# 2. Setup Certbot Directories
mkdir -p ./certbot/www
mkdir -p ./nginx

# 3. Handle SSL Setup
${enableSSL ? `
if [ ! -d "/etc/letsencrypt/live/${domain}" ]; then
    echo "🔒 Requesting Initial Let's Encrypt SSL Certificate for ${domain}..."
    docker run -it --rm -v $(pwd)/certbot/www:/var/www/certbot certbot/certbot certonly --webroot -w /var/www/certbot -d ${domain} --email ${email} --agree-tos --non-interactive || echo "⚠️ Self-signed SSL fallback"
fi
` : ''}

# 4. Pull, Build and Launch Stack
echo "📦 Building and starting production containers..."
docker compose -f docker-compose.prod.yml up -d --build --remove-orphans

# 5. Clean Dangling Images
docker image prune -f

echo ""
echo "=================================================="
echo "  🎉 Production Stack is LIVE & HEALTHY!"
echo "  🌐 URL: https://${domain}"
echo "=================================================="
`;
}

function generateDeployScriptPs1(domain: string): string {
  return `# ==============================================================================
# 🚀 ZERO-CODE WINDOWS PRODUCTION DEPLOYMENT SCRIPT
# Target Domain: ${domain}
# ==============================================================================

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "  🚀 Starting Production Deployment (${domain})" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

# 1. Verify Docker is running
docker --version
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Docker is not running. Please start Docker Desktop!" -ForegroundColor Red
    Exit 1
}

# 2. Build & Launch Production Stack
Write-Host "\`n📦 Launching production-hardened containers..." -ForegroundColor Yellow
docker compose -f docker-compose.prod.yml up -d --build --remove-orphans

if ($LASTEXITCODE -eq 0) {
    Write-Host "\`n🎉 Production Stack is LIVE & RUNNING!" -ForegroundColor Green
    Write-Host "🌐 Access: http://localhost (or https://${domain})" -ForegroundColor Green
} else {
    Write-Host "\`n❌ Deployment failed! Check docker logs." -ForegroundColor Red
}
`;
}

function generateProductionMakefile(): string {
  return `# ==============================================================================
# 🛠️ PRODUCTION OPS MAKEFILE
# ==============================================================================

.PHONY: prod down logs ps restart backup-db clean

prod:
	docker compose -f docker-compose.prod.yml up -d --build --remove-orphans

down:
	docker compose -f docker-compose.prod.yml down

logs:
	docker compose -f docker-compose.prod.yml logs -f --tail=100

ps:
	docker compose -f docker-compose.prod.yml ps

restart:
	docker compose -f docker-compose.prod.yml restart

backup-db:
	@mkdir -p ./backups
	@docker exec prod_db_postgres pg_dumpall -U postgres > ./backups/backup-$$(date +%Y%m%d%H%M%S).sql
	@echo "✅ Database backup created in ./backups"

clean:
	docker system prune -af --volumes
`;
}

function generateProductionEnvFile(services: DockerService[]): string {
  const lines: string[] = [
    '# ==============================================================================',
    '# 🔒 PRODUCTION CRYPTOGRAPHICALLY HARDENED ENVIRONMENT SECRETS',
    '# Generated by DockCraft Studio Vault',
    '# ==============================================================================',
    'NODE_ENV=production',
    'ENVIRONMENT=production',
    'PORT=80',
    '',
  ];

  services.forEach((s) => {
    if (s.env.length > 0) {
      lines.push(`# --- ${s.displayName} (${s.name}) ---`);
      s.env.forEach((e) => {
        lines.push(`${e.key}=${e.value}`);
      });
      lines.push('');
    }
  });

  return lines.join('\n');
}
