export type ServiceCategory = 
  | 'database' 
  | 'backend' 
  | 'frontend' 
  | 'gateway' 
  | 'queue' 
  | 'tool' 
  | 'ai' 
  | 'custom';

export interface PortMapping {
  id: string;
  hostPort: number | string;
  containerPort: number | string;
  protocol?: 'tcp' | 'udp';
  description?: string;
}

export interface VolumeMapping {
  id: string;
  hostPath: string;
  containerPath: string;
  type: 'volume' | 'bind';
  readOnly?: boolean;
  description?: string;
}

export interface EnvVariable {
  id: string;
  key: string;
  value: string;
  isSecret?: boolean;
  description?: string;
  autoGenerated?: boolean;
}

export interface HealthCheck {
  enabled: boolean;
  test: string;
  interval?: string;
  timeout?: string;
  retries?: number;
  startPeriod?: string;
}

export interface ResourceLimits {
  cpus?: string;
  memory?: string;
}

export interface DockerService {
  id: string;
  name: string;
  displayName: string;
  category: ServiceCategory;
  image?: string;
  tag?: string;
  icon: string;
  color: string;
  description: string;
  
  // Build info
  isCustomBuild: boolean;
  buildContext?: string;
  dockerfilePath?: string;
  dockerfileType?: 'nodejs' | 'python-fastapi' | 'python-flask' | 'go' | 'rust' | 'java-spring' | 'php-laravel' | 'nextjs' | 'react-vite' | 'custom';
  customDockerfileContent?: string;

  // Networking & Ports
  ports: PortMapping[];
  expose: number[];
  networks: string[];
  
  // Environment
  env: EnvVariable[];
  
  // Storage
  volumes: VolumeMapping[];
  
  // Dependencies & Lifecycle
  dependsOn: {
    serviceId: string;
    condition: 'service_started' | 'service_healthy' | 'service_completed_successfully';
  }[];
  
  healthCheck?: HealthCheck;
  restart: 'no' | 'always' | 'on-failure' | 'unless-stopped';
  command?: string;
  entrypoint?: string;
  user?: string;
  workingDir?: string;
  
  // Resource allocation
  resources?: ResourceLimits;
  
  // Extra metadata
  notes?: string;
}

export interface DockerNetwork {
  name: string;
  driver?: 'bridge' | 'overlay' | 'host' | 'none';
  external?: boolean;
}

export interface DockerVolume {
  name: string;
  driver?: string;
  external?: boolean;
}

export interface SecurityIssue {
  id: string;
  serviceId?: string;
  level: 'critical' | 'warning' | 'info' | 'success';
  title: string;
  message: string;
  fixSuggestion?: string;
  autoFixable?: boolean;
}

export interface ArchitectureTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  icon: string;
  services: Partial<DockerService>[];
  connections: { sourceId: string; targetId: string; type?: string }[];
}

export interface Project {
  id: string;
  name: string;
  description: string;
  services: DockerService[];
  createdAt: string;
  updatedAt: string;
}
